"""add processing stage to documents

Revision ID: 01fd29b81c56
Revises: 130d7d529d81
Create Date: 2026-09-07 22:33:21.262683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01fd29b81c56'
down_revision: Union[str, Sequence[str], None] = '130d7d529d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "documents",
        sa.Column(
            "processing_stage",
            sa.String(length=50),
            nullable=False,
            server_default="uploaded",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_stage')
    # ### end Alembic commands ###
