"""add document processing logs

Revision ID: 4775ab64574e
Revises: 01fd29b81c56
Create Date: 2026-09-09 20:45:04.026101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4775ab64574e'
down_revision: Union[str, Sequence[str], None] = '01fd29b81c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_processing_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_processing_logs_document_id'), 'document_processing_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_processing_logs_id'), 'document_processing_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_processing_logs_id'), table_name='document_processing_logs')
    op.drop_index(op.f('ix_document_processing_logs_document_id'), table_name='document_processing_logs')
    op.drop_table('document_processing_logs')
    # ### end Alembic commands ###
